FROM quay.io/argoproj/argocd:v2.13.1
USER root
# tools
RUN apt-get update; apt-get install -y telnet curl tmux net-tools dnsutils gnupg wget
# for gcp sdk
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg > /usr/share/keyrings/cloud.google.gpg
#RUN wget https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x35baa0b33e9eb396f59ca838c0ba5ce6dc6315a3|apt-key add -
RUN echo "deb https://packages.cloud.google.com/apt cloud-sdk main" >  /etc/apt/sources.list.d/google-cloud-sdk.list
RUN apt-get update && apt-get install -y google-cloud-cli google-cloud-sdk-gke-gcloud-auth-plugin
RUN curl -o /usr/local/bin/kubectl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x /usr/local/bin/kubectl
COPY google-root.crt  intermediate.crt /etc/ssl/certs/
RUN /usr/sbin/update-ca-certificates
USER 999
